name: Arduino

on: [push, pull_request]

jobs:
  build:
    
    runs-on: ubuntu-latest

    env:
      PLATFORM_DEFAULT_URL: https://arduino.esp8266.com/stable/package_esp8266com_index.json
      REQUIRED_LIBRARIES: Servo,Adafruit NeoPixel
    strategy:
      matrix:
        arduino-boards-fqbn:
          - esp8266:esp8266:nodemcuv2:xtal=80,vt=flash,exception=disabled,eesz=4M1M,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v2
      with:
        arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }} 
        platform-url: ${{ env.PLATFORM_DEFAULT_URL }}
        required-libraries: ${{ env.REQUIRED_LIBRARIES }}
